# model name, i.e. dvelopment, RNN, LSTM, signature
model: LSTM_DEV
# paramterisation if development is used, SO, Sp
param: SO #SO,Sp
# dataset SpeechCommands
dataset: SpeechCommands
# cuda, cpu
device: cuda
gpu_id: "0"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 1
patience: 10
weight_decay: 0
lr: 0.001
n_hidden1: 10
n_hidden2: 5
batch_size: 200
epochs: 300 #150
mfcc: True
comment:
